### ISSUE TITLE
YAML load function deprecated

### ISSUE THREAD

**Issue by hanyas** [gregorgebhardt/cluster_work#1]
https://github.com/gregorgebhardt/cluster_work/blob/6acbb6d659c19054279bd45f89feb6af056d741f/cluster_work.py#L323

In the recent yaml package the current load function gives out an ugly warning. Easiest way to resolve it is to specify the loader.

https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

**Comment by gregorgebhardt** [comment]
Will drop that for gin files anyways...
